server:
  port: 9500
spring:
  application:
    name: eureka-application-consumer  # 指定当前应用名 如果不配置 instance-id 那么此项为客户端在注册中心的名称默认值
eureka:
  instance:
    instance-id: consumer-application  # 指定当前客户端在注册中心的名称
  client:
    service-url:
      defaultZone: http://localhost:8300/eureka  # 服务中心的地址 就是我们在 Eureka Server 中配置的暴露地址